/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kevin.jni.jniworld;

public class HelloJNI {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected HelloJNI(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HelloJNI obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JniExampleJNI.delete_HelloJNI(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    JniExampleJNI.HelloJNI_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    JniExampleJNI.HelloJNI_change_ownership(this, swigCPtr, true);
  }

  public HelloJNI(String say) {
    this(JniExampleJNI.new_HelloJNI(say), true);
    JniExampleJNI.HelloJNI_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public String getString() {
    return JniExampleJNI.HelloJNI_getString(swigCPtr, this);
  }

  public void callBack() {
    if (getClass() == HelloJNI.class) JniExampleJNI.HelloJNI_callBack(swigCPtr, this); else JniExampleJNI.HelloJNI_callBackSwigExplicitHelloJNI(swigCPtr, this);
  }

}
