/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kevin.jni.jniworld;

public class JniExample {
  public static String getLibrarySaySth() {
    return JniExampleJNI.getLibrarySaySth();
  }

  public static void request(HelloJNI helloJNI) {
    JniExampleJNI.request(HelloJNI.getCPtr(helloJNI), helloJNI);
  }

}
