/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kevin.jni.jniworld;

public class JniExampleJNI {
  public final static native long new_HelloJNI(String jarg1);
  public final static native String HelloJNI_getString(long jarg1, HelloJNI jarg1_);
  public final static native void HelloJNI_callBack(long jarg1, HelloJNI jarg1_);
  public final static native void HelloJNI_callBackSwigExplicitHelloJNI(long jarg1, HelloJNI jarg1_);
  public final static native void delete_HelloJNI(long jarg1);
  public final static native void HelloJNI_director_connect(HelloJNI obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void HelloJNI_change_ownership(HelloJNI obj, long cptr, boolean take_or_release);
  public final static native String getLibrarySaySth();
  public final static native void request(long jarg1, HelloJNI jarg1_);

  public static void SwigDirector_HelloJNI_callBack(HelloJNI jself) {
    jself.callBack();
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
