/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kevin_java_jni_HelloJNI */

#ifndef _Included_com_kevin_java_jni_HelloJNI
#define _Included_com_kevin_java_jni_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kevin_java_jni_HelloJNI
 * Method:    getHelloString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kevin_java_jni_HelloJNI_getHelloString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
